version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:

  db:
    image: postgres:13.0
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  yamdb:
    #image: alexandrbatanov/yamdb_final:latest
    build: .
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - media_volume:/var/html/media/
      - static_volume:/var/html/static/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - yamdb
